from uuid import UUID, uuid4
from pydantic import ConfigDict
from sqlmodel import SQLModel, Field, Column, TIMESTAMP
from datetime import datetime, timezone

class EventTypeBase(SQLModel):
    name: str
    is_active: bool = Field(default=True)

class EventType(EventTypeBase, table=True):
    __tablename__ = "event_types"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    code: str = Field(index=True, unique=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True), onupdate=lambda: datetime.now(timezone.utc))
    )

class EventTypeCreate(EventTypeBase):
    model_config = ConfigDict(extra="forbid")
    # event_type.id is auto-generated by the DB
    code: str

class EventTypeUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")
    # event_type.id is used to update the event type
    # event_type.code is not updatable, delete and recreate if needed
    name: str | None = None
    is_active: bool | None = None