from uuid import UUID, uuid4
from pydantic import ConfigDict
from sqlmodel import SQLModel, Field, Column, TIMESTAMP
from datetime import datetime, timezone

class ProficiencyLevelBase(SQLModel):
    name: str
    rank: int | None = Field(default=None)
    is_active: bool = Field(default=True)
    is_assignable: bool = Field(default=False)

class ProficiencyLevel(ProficiencyLevelBase, table=True):
    __tablename__ = "proficiency_levels"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    code: str = Field(index=True, unique=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True), onupdate=lambda: datetime.now(timezone.utc))
    )

class ProficiencyLevelCreate(ProficiencyLevelBase):
    model_config = ConfigDict(extra="forbid")
    # proficiency_level.id is auto-generated by the DB
    code: str

class ProficiencyLevelUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")
    # proficiency_level.id is used to update the proficiency level
    # proficiency_level.code is not updatable, delete and recreate if needed
    name: str | None = None
    rank: int | None = None
    is_active: bool | None = None
    is_assignable: bool | None = None