from typing import TYPE_CHECKING
from uuid import UUID, uuid4
from pydantic import ConfigDict
from sqlmodel import SQLModel, Field, Relationship, Column, TIMESTAMP
from datetime import datetime, timezone

if TYPE_CHECKING:
    from app.db.models import UserRole

class RoleBase(SQLModel):
    name: str
    description: str | None = Field(default=None)
    order: int
    is_active: bool = Field(default=True)

class Role(RoleBase, table=True):
    __tablename__ = "roles"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    code: str = Field(index=True, unique=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True), onupdate=lambda: datetime.now(timezone.utc))
    )

    # Relationships
    user_roles: list["UserRole"] = Relationship(back_populates="role", sa_relationship_kwargs={"cascade": "all, delete-orphan"})

class RoleCreate(RoleBase):
    model_config = ConfigDict(extra="forbid")
    # role.id is auto-generated by the DB
    code: str

class RoleUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")
    # role.id is used to update the role
    # role.code is not updatable, delete and recreate if needed
    name: str | None = None
    description: str | None = None
    order: int | None = None
    is_active: bool | None = None