from uuid import UUID, uuid4
from pydantic import ConfigDict
from typing import TYPE_CHECKING
from sqlmodel import SQLModel, Field, Relationship, CheckConstraint, Column, TIMESTAMP
from datetime import datetime, timezone

if TYPE_CHECKING:
    from app.db.models import Event, EventWithAssignmentsAndAvailabilityPublic

class ScheduleBase(SQLModel):
    is_active: bool = Field(default=True)
    notes: str | None = Field(default=None)

class Schedule(ScheduleBase, table=True):
    __tablename__ = "schedules"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    month: int
    year: int
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True), onupdate=lambda: datetime.now(timezone.utc))
    )

    # Relationships
    events: list["Event"] = Relationship(back_populates="schedule")

    __table_args__ = (
        CheckConstraint("month >= 1 AND month <= 12", name="schedule_check_month"),
    )

class ScheduleCreate(ScheduleBase):
    model_config = ConfigDict(extra="forbid")
    # schedule.id is auto-generated by the DB
    month: int
    year: int

class ScheduleUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")
    # schedule.id is used to update the schedule
    is_active: bool | None = None
    notes: str | None = None

class ScheduleGridPublic(SQLModel):
    schedule: Schedule
    events: list["EventWithAssignmentsAndAvailabilityPublic"]

    @classmethod
    def from_objects(cls, schedule: "Schedule", events: list["EventWithAssignmentsAndAvailabilityPublic"]):
        """Create a ScheduleGridPublic from the related objects."""
        return cls(
            schedule=schedule,
            events=events
        )