from uuid import UUID, uuid4
from typing import TYPE_CHECKING
from pydantic import ConfigDict
from sqlmodel import SQLModel, Field, Relationship, Column, TIMESTAMP
from datetime import datetime, timezone

if TYPE_CHECKING:
    from app.db.models import TeamUser

class TeamBase(SQLModel):
    name: str
    is_active: bool = Field(default=True)

class Team(TeamBase, table=True):
    __tablename__ = "teams"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    code: str = Field(index=True, unique=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True), onupdate=lambda: datetime.now(timezone.utc))
    )

    # Relationships
    team_users: list["TeamUser"] = Relationship(back_populates="team", sa_relationship_kwargs={"cascade": "all, delete-orphan"})

class TeamCreate(TeamBase):
    model_config = ConfigDict(extra="forbid")
    # team.id is auto-generated by the DB
    code: str

class TeamUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")
    # team.id is used to update the team
    name: str | None = None
    is_active: bool | None = None