from uuid import UUID, uuid4
from typing import TYPE_CHECKING
from pydantic import ConfigDict
from sqlmodel import SQLModel, Field, Relationship, Column, ForeignKey, UniqueConstraint, TIMESTAMP
from datetime import datetime, timezone

if TYPE_CHECKING:
    from app.db.models import Team, User

class TeamUserBase(SQLModel):
    is_active: bool = Field(default=True)

class TeamUser(TeamUserBase, table=True):
    __tablename__ = "team_users"
    
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    team_id: UUID = Field(sa_column=Column(ForeignKey("teams.id", ondelete="CASCADE"), index=True, nullable=False))
    user_id: UUID = Field(sa_column=Column(ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False))
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True), onupdate=lambda: datetime.now(timezone.utc))
    )

    # Relationships
    team: "Team" = Relationship(back_populates="team_users")
    user: "User" = Relationship()

    __table_args__ = (
        UniqueConstraint("team_id", "user_id", name="team_user_ukey"),
    )

class TeamUserCreate(TeamUserBase):
    model_config = ConfigDict(extra="forbid")
    # team_user.id is auto-generated by the DB
    # team_id is provided in the URL path
    user_id: UUID # provided in the payload

class TeamUserUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")
    # team_user.team_id + team_user.user_id is used to update the team user
    is_active: bool | None = None

class TeamUserPublic(TeamUserBase):
    id: UUID
    team_id: UUID
    user_id: UUID
    # join fields
    team_name: str
    team_code: str
    team_is_active: bool
    user_first_name: str
    user_last_name: str
    user_email: str | None
    user_phone: str
    user_is_active: bool
    
    @classmethod
    def from_objects(
        cls,
        team_user: "TeamUser",
        team: "Team",
        user: "User",
    ):
        """Create a TeamUserPublic from the related objects."""
        return cls(
            id=team_user.id,
            team_id=team_user.team_id,
            user_id=team_user.user_id,
            is_active=team_user.is_active,
            team_name=team.name,
            team_code=team.code,
            team_is_active=team.is_active,
            user_first_name=user.first_name,
            user_last_name=user.last_name,
            user_email=user.email,
            user_phone=user.phone,
            user_is_active=user.is_active,
        )