from uuid import UUID, uuid4
from pydantic import ConfigDict
from typing import TYPE_CHECKING
from sqlmodel import SQLModel, Field, Relationship, Column, ForeignKey, CheckConstraint, TIMESTAMP
from datetime import datetime, timezone

if TYPE_CHECKING:
    from app.db.models import User

class UserUnavailablePeriodBase(SQLModel):
    starts_at: datetime = Field(sa_column=Column(TIMESTAMP(timezone=True), index=True))
    ends_at: datetime = Field(sa_column=Column(TIMESTAMP(timezone=True)))

class UserUnavailablePeriod(UserUnavailablePeriodBase, table=True):
    __tablename__ = "user_unavailable_periods"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(sa_column=Column(ForeignKey("users.id"), index=True, nullable=False))
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True))
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(TIMESTAMP(timezone=True), onupdate=lambda: datetime.now(timezone.utc))
    )

    # Relationships
    user: "User" = Relationship(back_populates="user_unavailable_periods")

    __table_args__ = (
        CheckConstraint("starts_at < ends_at", name="user_unavailable_period_check_time_range"),
    )

class UserUnavailablePeriodCreate(UserUnavailablePeriodBase):
    model_config = ConfigDict(extra="forbid")
    # user_unavailable_period.id is auto-generated by the DB
    user_id: UUID

class UserUnavailablePeriodUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")
    # user_id is not updatable, delete and recreate if needed
    starts_at: datetime | None = None
    ends_at: datetime | None = None

class UserUnavailablePeriodPublic(UserUnavailablePeriodBase):
    id: UUID
    user_id: UUID
    # join fields
    user_first_name: str
    user_last_name: str
    user_email: str | None
    user_phone: str
    user_is_active: bool