"""add cascade deletes

Revision ID: 846f1220addc
Revises: 834989ea2cbe
Create Date: 2025-12-25 10:21:47.240755

"""
from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846f1220addc'
down_revision: Union[str, Sequence[str], None] = '834989ea2cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_assignments_event_id_fkey'), 'event_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'event_assignments', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('events_schedule_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('team_users_user_id_fkey'), 'team_users', type_='foreignkey')
    op.drop_constraint(op.f('team_users_team_id_fkey'), 'team_users', type_='foreignkey')
    op.create_foreign_key(None, 'team_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_users', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'team_users', type_='foreignkey')
    op.drop_constraint(None, 'team_users', type_='foreignkey')
    op.create_foreign_key(op.f('team_users_team_id_fkey'), 'team_users', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('team_users_user_id_fkey'), 'team_users', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_schedule_id_fkey'), 'events', 'schedules', ['schedule_id'], ['id'])
    op.drop_constraint(None, 'event_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('event_assignments_event_id_fkey'), 'event_assignments', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
