import datetime
from uuid import UUID
from pydantic import BaseModel

# =============================
# MEDIA ROLES
# =============================
class MediaRoleBase(BaseModel):
    media_role_name: str | None = None
    description: str | None = None
    sort_order: int | None = None
    is_active: bool | None = None
    media_role_code: str | None = None

class MediaRoleCreate(MediaRoleBase):
    # media_role_id is auto-generated by the DB
    media_role_name: str
    # description is optional
    sort_order: int
    media_role_code: str 
    # is_active is defaulted by the DB

class MediaRoleUpdate(MediaRoleBase):
    pass

class MediaRoleOut(MediaRoleBase):
    media_role_id: UUID

# =============================
# PROFICIENCY LEVELS
# =============================
class ProficiencyLevelBase(BaseModel):
    proficiency_level_name: str | None = None
    proficiency_level_number: int | None = None
    is_active: bool | None = None
    proficiency_level_code: str | None = None
    is_assignable: bool | None = None

class ProficiencyLevelCreate(ProficiencyLevelBase):
    # proficiency_level_id is auto-generated by the DB
    proficiency_level_name: str
    # proficiency_level_number is optional
    proficiency_level_code: str 
    # is_active is defaulted by the DB
    # is_assignable is defaulted by the DB

class ProficiencyLevelUpdate(ProficiencyLevelBase):
    pass

class ProficiencyLevelOut(ProficiencyLevelBase):
    proficiency_level_id: UUID

# =============================
# SCHEDULE DATE TYPES
# =============================
class ScheduleDateTypeBase(BaseModel):
    schedule_date_type_name: str | None = None
    is_active: bool | None = None
    schedule_date_type_code: str | None = None

class ScheduleDateTypeCreate(ScheduleDateTypeBase):
    # schedule_date_type_id is auto-generated by the DB
    schedule_date_type_name: str
    schedule_date_type_code: str 
    # is_active is defaulted by the DB

class ScheduleDateTypeUpdate(ScheduleDateTypeBase):
    pass

class ScheduleDateTypeOut(ScheduleDateTypeBase):
    schedule_date_type_id: UUID

# =============================
# TEAMS
# =============================
class TeamBase(BaseModel):
    team_name: str | None = None
    is_active: bool | None = None
    team_code: str | None = None

class TeamCreate(TeamBase):
    # team_id is auto-generated by the DB
    team_name: str
    team_code: str 
    # is_active is defaulted by the DB

class TeamUpdate(TeamBase):
    pass

class TeamOut(TeamBase):
    team_id: UUID

# =============================
# USERS
# =============================
class UserBase(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    email: str | None = None
    phone: str | None = None
    is_active: bool | None = None

class UserCreate(UserBase):
    # user_id is auto-generated by the DB
    first_name: str 
    last_name: str 
    # email is optional
    phone: str 
    # is_active is defaulted by the DB

class UserUpdate(UserBase):
    pass

class UserOut(UserBase):
    user_id: UUID

# =============================
# TEAM USERS
# =============================
class TeamUserBase(BaseModel):
    team_id: UUID | None = None
    user_id: UUID | None = None
    is_active: bool | None = None

class TeamUserCreate(TeamUserBase):
    # team_user_id is auto-generated by the DB
    team_id: UUID
    user_id: UUID
    # is_active is defaulted by the DB

class TeamUserUpdate(TeamUserBase):
    pass

class TeamUserOut(TeamUserBase):
    team_user_id: UUID

# =============================
# USER ROLES
# =============================
class UserRoleBase(BaseModel):
    user_id: UUID | None = None
    media_role_id: UUID | None = None
    proficiency_level_id: UUID | None = None

class UserRoleCreate(UserRoleBase):
    # user_role_id is auto-generated by the DB
    user_id: UUID
    media_role_id: UUID
    proficiency_level_id: UUID

class UserRoleUpdate(UserRoleBase):
    pass

class UserRoleOut(UserRoleBase):
    user_role_id: UUID

# =============================
# DATES
# =============================
class DateBase(BaseModel):
    calendar_year: int | None = None
    calendar_month: int | None = None
    month_name: str | None = None
    month_abbr: str | None = None
    calendar_day: int | None = None
    weekday: int | None = None
    weekday_name: str | None = None
    is_weekend: bool | None = None
    is_weekday: bool | None = None
    is_holiday: bool | None = None
    week_number: int | None = None
    is_first_of_month: bool | None = None
    is_last_of_month: bool | None = None
    calendar_quarter: int | None = None
    weekday_of_month: int | None = None 

class DateCreate(BaseModel):
    date: datetime.date
    # do not inherit from DateBase, all other fields will be automatically calculated

class DateUpdate(DateBase):
    pass

class DateOut(DateBase):
    date: datetime.date

# =============================
# SCHEDULES
# =============================
class ScheduleBase(BaseModel):
    month_start_date: datetime.date | None = None
    is_active: bool | None = None
    notes: str | None = None

class ScheduleCreate(ScheduleBase):
    # schedule_id is auto-generated by the DB
    month_start_date: datetime.date
    # is_active is defaulted by the DB

class ScheduleUpdate(ScheduleBase):
    pass

class ScheduleOut(ScheduleBase):
    schedule_id: UUID

# =============================
# SCHEDULE DATES
# =============================
class ScheduleDateBase(BaseModel):
    schedule_id: UUID | None = None
    date: datetime.date | None = None
    team_id: UUID | None = None
    schedule_date_type_id: UUID | None = None
    notes: str | None = None
    is_active: bool | None = None

class ScheduleDateCreate(ScheduleDateBase):
    # schedule_date_id is auto-generated by the DB
    schedule_id: UUID
    date: datetime.date
    # team_id is optional
    schedule_date_type_id: UUID
    # notes is optional
    # is_active is defaulted by the DB

class ScheduleDateUpdate(ScheduleDateBase):
    pass

class ScheduleDateOut(ScheduleDateBase):
    schedule_date_id: UUID

# =============================
# SCHEDULE DATE ROLES
# =============================
class ScheduleDateRoleBase(BaseModel):
    schedule_date_id: UUID | None = None
    media_role_id: UUID | None = None
    is_required: bool | None = None
    is_preferred: bool | None = None
    assigned_user_id: UUID | None = None
    is_active: bool | None = None

class ScheduleDateRoleCreate(ScheduleDateRoleBase):
    # schedule_date_role_id is auto-generated by the DB
    schedule_date_id: UUID
    media_role_id: UUID
    # is_required is defaulted by the DB
    # is_preferred is defaulted by the DB
    # assigned_user_id is optional
    # is_active is defaulted by the DB

class ScheduleDateRoleUpdate(ScheduleDateRoleBase):
    pass

class ScheduleDateRoleOut(ScheduleDateRoleBase):
    schedule_date_role_id: UUID

# =============================
# USER AVAILABILITY
# =============================
class UserAvailabilityBase(BaseModel):
    user_id: UUID | None = None
    date: datetime.date | None = None

class UserAvailabilityCreate(UserAvailabilityBase):
    # user_availability_id is auto-generated by the DB
    user_id: UUID
    date: datetime.date

class UserAvailabilityUpdate(UserAvailabilityBase):
    pass

class UserAvailabilityOut(UserAvailabilityBase):
    user_availability_id: UUID