from uuid import UUID
from pydantic import BaseModel

class ProficiencyLevelBase(BaseModel):
    proficiency_level_name: str | None = None
    proficiency_level_number: int | None = None
    is_active: bool | None = None
    proficiency_level_code: str | None = None
    is_assignable: bool | None = None

class ProficiencyLevelCreate(ProficiencyLevelBase):
    # proficiency_level_id is auto-generated by the DB
    proficiency_level_name: str
    # proficiency_level_number is optional
    proficiency_level_code: str 
    # is_active is defaulted by the DB
    # is_assignable is defaulted by the DB

class ProficiencyLevelUpdate(ProficiencyLevelBase):
    pass

class ProficiencyLevelOut(ProficiencyLevelBase):
    proficiency_level_id: UUID