from uuid import UUID
from pydantic import BaseModel

class ScheduleDateTypeBase(BaseModel):
    schedule_date_type_name: str | None = None
    is_active: bool | None = None
    schedule_date_type_code: str | None = None

class ScheduleDateTypeCreate(ScheduleDateTypeBase):
    # schedule_date_type_id is auto-generated by the DB
    schedule_date_type_name: str
    schedule_date_type_code: str 
    # is_active is defaulted by the DB

class ScheduleDateTypeUpdate(ScheduleDateTypeBase):
    pass

class ScheduleDateTypeOut(ScheduleDateTypeBase):
    schedule_date_type_id: UUID