import datetime

from uuid import UUID
from pydantic import BaseModel

class ScheduleDateBase(BaseModel):
    schedule_id: UUID | None = None
    date: datetime.date | None = None
    team_id: UUID | None = None
    schedule_date_type_id: UUID | None = None
    notes: str | None = None
    is_active: bool | None = None

class ScheduleDateCreate(ScheduleDateBase):
    # schedule_date_id is auto-generated by the DB
    schedule_id: UUID
    date: datetime.date
    # team_id is optional
    schedule_date_type_id: UUID
    # notes is optional
    # is_active is defaulted by the DB

class ScheduleDateUpdate(ScheduleDateBase):
    pass

class ScheduleDateOut(ScheduleDateBase):
    schedule_date_id: UUID