from datetime import date

from uuid import UUID
from pydantic import BaseModel

class ScheduleBase(BaseModel):
    month_start_date: date | None = None
    is_active: bool | None = None
    notes: str | None = None

class ScheduleCreate(ScheduleBase):
    # schedule_id is auto-generated by the DB
    month_start_date: date
    # is_active is defaulted by the DB

class ScheduleUpdate(ScheduleBase):
    pass

class ScheduleOut(ScheduleBase):
    schedule_id: UUID