from uuid import UUID
from pydantic import BaseModel

class TeamUserBase(BaseModel):
    team_id: UUID | None = None
    user_id: UUID | None = None
    is_active: bool | None = None

class TeamUserCreate(TeamUserBase):
    # team_user_id is auto-generated by the DB
    team_id: UUID
    user_id: UUID
    # is_active is defaulted by the DB

class TeamUserUpdate(TeamUserBase):
    pass

class TeamUserOut(TeamUserBase):
    team_user_id: UUID