from uuid import UUID
from pydantic import BaseModel

class UserBase(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    email: str | None = None
    phone: str | None = None
    is_active: bool | None = None

class UserCreate(UserBase):
    # user_id is auto-generated by the DB
    first_name: str 
    last_name: str 
    # email is optional
    phone: str 
    # is_active is defaulted by the DB

class UserUpdate(UserBase):
    pass

class UserOut(UserBase):
    user_id: UUID