import datetime

from uuid import UUID
from pydantic import BaseModel

class UserAvailabilityBase(BaseModel):
    user_id: UUID | None = None
    date: datetime.date | None = None

class UserAvailabilityCreate(UserAvailabilityBase):
    # user_availability_id is auto-generated by the DB
    user_id: UUID
    date: datetime.date

class UserAvailabilityUpdate(UserAvailabilityBase):
    pass

class UserAvailabilityOut(UserAvailabilityBase):
    user_availability_id: UUID