from uuid import UUID
from pydantic import BaseModel

class UserRoleBase(BaseModel):
    user_id: UUID | None = None
    media_role_id: UUID | None = None
    proficiency_level_id: UUID | None = None

class UserRoleCreate(UserRoleBase):
    # user_role_id is auto-generated by the DB
    user_id: UUID
    media_role_id: UUID
    proficiency_level_id: UUID

class UserRoleUpdate(UserRoleBase):
    pass

class UserRoleOut(UserRoleBase):
    user_role_id: UUID